import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";                                            // need for Link component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Add component to link to other folders
function Header() {
  return (
    <header>
      <div>
        <nav>
          <div>
            <Link href = "/">Home</Link>
          </div>
          <div>
            <Link href = "/mountain">Mountain Info</Link>
          </div>
          <div>
            <Link href = "/hotel">Hotel Info</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

// Add Header Component to be seen in all pages
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <Header />
        {children}
      </body>
    </html>
  );
}